#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import wyzepal

usage = """delete-stream <stream_id>

Example: delete-stream 42
"""


parser = wyzepal.add_default_arguments(argparse.ArgumentParser(usage=usage))
parser.add_argument('stream_id', type=int)
options = parser.parse_args()

client = wyzepal.init_from_options(options)

print(client.delete_stream(options.stream_id))
