#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import wyzepal

usage = """get-raw-message <message_id> [options]


Example: get-raw-message 42
"""


parser = wyzepal.add_default_arguments(argparse.ArgumentParser(usage=usage))
parser.add_argument('message_id', type=int)
options = parser.parse_args()

client = wyzepal.init_from_options(options)

print(client.get_raw_message(options.message_id))
