#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import wyzepal

usage = """message-history <message_id> [options]

Example: message-history 42
"""

parser = wyzepal.add_default_arguments(argparse.ArgumentParser(usage=usage))
parser.add_argument('message_id', type=int)
options = parser.parse_args()

client = wyzepal.init_from_options(options)

print(client.get_message_history(options.message_id))
