#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse

import wyzepal

usage = """realm-emoji [options]

Example: realm-emoji
"""

parser = wyzepal.add_default_arguments(argparse.ArgumentParser(usage=usage))
options = parser.parse_args()

client = wyzepal.init_from_options(options)

print(client.get_realm_emoji())
